{
  "modified": "2025-10-07T18:22:46Z",
  "published": "2025-10-07T18:10:05Z",
  "schema_version": "1.5.0",
  "id": "CVE-2025-8291",
  "aliases": [
    "PSF-2025-12"
  ],
  "details": "The 'zipfile' module would not check the validity of the ZIP64 End of\nCentral Directory (EOCD) Locator record offset value would not be used to\nlocate the ZIP64 EOCD record, instead the ZIP64 EOCD record would be\nassumed to be the previous record in the ZIP archive. This could be abused\nto create ZIP archives that are handled differently by the 'zipfile' module\ncompared to other ZIP implementations.\n\n\nRemediation maintains this behavior, but checks that the offset specified\nin the ZIP64 EOCD Locator record matches the expected value.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/pull/139702"
    },
    {
      "type": "ADVISORY",
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/QECOPWMTH4VPPJAXAH2BGTA4XADOP62G/"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/python/cpython/issues/139700"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/162997bb70e067668c039700141770687bc8f267"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/333d4a6f4967d3ace91492a39ededbcf3faa76a6"
    }
  ]
}