{
  "modified": "2023-08-25T16:05:33Z",
  "published": "2019-06-03T19:04:24Z",
  "schema_version": "1.5.0",
  "id": "CVE-2013-1752",
  "aliases": [
    "PSF-2019-1"
  ],
  "details": "The smtplib module doesn't limit the amount of read data in\nits call to readline(). An erroneous or malicious SMTP server can trick the\nsmtplib module to consume large amounts of memory.\n",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.6.9-rc1"
            },
            {
              "introduced": "2.7.0"
            },
            {
              "fixed": "2.7.2-rc1"
            },
            {
              "introduced": "2.7.3"
            },
            {
              "fixed": "2.7.4-rc1"
            },
            {
              "introduced": "2.7.5"
            },
            {
              "fixed": "2.7.6-rc1"
            },
            {
              "introduced": "2.7.8"
            },
            {
              "fixed": "2.7.9"
            },
            {
              "introduced": "2.7.15"
            },
            {
              "fixed": "2.7.16-rc1"
            },
            {
              "introduced": "3.2.0"
            },
            {
              "fixed": "3.2.6"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/security/cve/cve-2013-1752"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue16038"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue16039"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue16040"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue16041"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue16042"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue6791"
    }
  ]
}