{
  "modified": "2025-06-26T16:49:31Z",
  "published": "2014-04-22T14:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2013-7338",
  "aliases": [
    "PSF-2014-3"
  ],
  "details": "Python before 3.3.4 RC1 allows remote attackers to cause a denial of service (infinite loop and CPU consumption) via a file size value larger than the size of the zip file to the (1) ZipExtFile.read, (2) ZipExtFile.read(n), (3) ZipExtFile.readlines, (4) ZipFile.extract, or (5) ZipFile.extractall function.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      }
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue20078"
    }
  ]
}