{
  "modified": "2023-08-25T16:05:33Z",
  "published": "2022-08-23T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2021-28861",
  "aliases": [
    "PSF-2022-5"
  ],
  "details": "Python 3.x through 3.10 has an open redirection vulnerability in lib/http/server.py due to no protection against multiple (/) at the beginning of URI path which may leads to information disclosure. NOTE: this is disputed by a third party because the http.server.html documentation page states \"Warning: http.server is not recommended for production. It only implements basic security checks.\"",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.7.0"
            },
            {
              "fixed": "3.7.14"
            },
            {
              "introduced": "3.8.0"
            },
            {
              "fixed": "3.8.14"
            },
            {
              "introduced": "3.9.0"
            },
            {
              "fixed": "3.9.14"
            },
            {
              "introduced": "3.10.0"
            },
            {
              "fixed": "3.10.6"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/security/cve/CVE-2021-28861"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/python/cpython/issues/87389"
    }
  ]
}