{
  "modified": "2022-07-25T16:13:15Z",
  "published": "2019-03-13T03:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2019-9740",
  "aliases": [
    "PSF-2019-10"
  ],
  "details": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.7.17-rc1"
            },
            {
              "introduced": "3.5.0-alpha1"
            },
            {
              "fixed": "3.5.8-rc1"
            },
            {
              "introduced": "3.6.0-alpha1"
            },
            {
              "fixed": "3.6.9-rc1"
            },
            {
              "introduced": "3.7.0-alpha1"
            },
            {
              "fixed": "3.7.4-rc1"
            },
            {
              "introduced": "3.8.0-alpha1"
            },
            {
              "fixed": "3.8.0-alpha4"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue30458"
    }
  ]
}