{
  "modified": "2023-08-25T16:05:33Z",
  "published": "2019-06-19T22:07:57Z",
  "schema_version": "1.5.0",
  "id": "CVE-2019-12900",
  "aliases": [
    "PSF-2019-4"
  ],
  "details": "BZ2_decompress in decompress.c in bzip2 through 1.0.6 has an out-of-bounds write when there are many selectors.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.7.0"
            },
            {
              "fixed": "3.7.13"
            },
            {
              "introduced": "3.8.0"
            },
            {
              "fixed": "3.8.13"
            },
            {
              "introduced": "3.9.0"
            },
            {
              "fixed": "3.9.11"
            },
            {
              "introduced": "3.10.0"
            },
            {
              "fixed": "3.10.3"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/security/cve/cve-2016-3189"
    },
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/security/cve/cve-2019-12900"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue44549"
    }
  ]
}