{
  "modified": "0001-01-01T00:00:00Z",
  "published": "2017-05-29T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "PSF-2017-9",
  "details": "The urllib module doesn't parse correctly password containing the ``#``\ncharacter.\n",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.7.14-rc1"
            },
            {
              "introduced": "3.3.0-alpha1"
            },
            {
              "fixed": "3.3.7-rc1"
            },
            {
              "introduced": "3.4.0-alpha1"
            },
            {
              "fixed": "3.4.7-rc1"
            },
            {
              "introduced": "3.5.0-alpha1"
            },
            {
              "fixed": "3.5.4-rc1"
            },
            {
              "introduced": "3.6.0-alpha1"
            },
            {
              "fixed": "3.6.2-rc2"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue30500"
    }
  ]
}